spring:
  main:
    cloud-platform: kubernetes
  application:
    name: master

  config:
    import: 'kubernetes:'

  cloud:
    kubernetes:
      config:
        namespace: istio-example
        enabled: true
      secrets:
        namespace: istio-example
        enable-api: true
      discovery:
        enabled: true
        all-namespaces: false
        namespaces:
          - istio-example
      reload:
        monitoring-config-maps: true
        enabled: true
        strategy: refresh
  profiles:
    active: dev

management:
  endpoint:
    refresh:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    org.springframework.cloud: info