spring:
  main:
    cloud-platform: kubernetes
  application:
    name: master

  config:
    import: 'kubernetes:'

  cloud:
    config:
      enabled: false
    kubernetes:
      config:
        name: master
        namespace: istio-example
        enabled: true

      client:
        master-url: "https://k8s-local:6443"
        trust-certs: true
        namespace: istio-example
        oauth-token: token
      discovery:
        enabled: true
        all-namespaces: false
        namespaces:
          - istio-example
      reload:
        monitoring-config-maps: true
        enabled: true
        strategy: refresh
  profiles:
    active: dev

management:
  endpoint:
    refresh:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    org.springframework.cloud: debug