apiVersion: v1
kind: Service
metadata:
  namespace: istio-example
  name: master
spec:
  selector:
    app: master
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30950
  type: NodePort
